all:
  vars:
    ansible_user: vagrant
    #ansible_password: vagrant
    #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
web:
  hosts:
    slave-1:
      ansible_host: 192.168.9.184

db:
  hosts:
    slave-2:
      ansible_host: 192.168.9.185
